name: Manually trigger an Azure Machine Learning job

on:
  push:
     branches:
       - main

jobs:
  train-dev:
    runs-on: ubuntu-latest
    environment:
      name: dev
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Trigger Azure ML job
      run: az ml job create --file src/job.yml --workspace-name MLOpsWorkspace --resource-group MLOps
  train-prod:
    runs-on: ubuntu-latest
    environment:
      name: prod
    needs:
      - train-dev
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Trigger Azure ML job
      run: az ml job create --file src/job-prod.yml --workspace-name MLOpsWorkspace --resource-group MLOps


